### PR TITLE
Song-Info popup improvements

### PR DESCRIPTION
**Pull request by janbaykara**
Polished up the song-info popup, and added a few useful features:
- [X] Countdown to scrobble timer (mentioned in #702)
- [X] Track/artist edit mode (may satisfy #245, #371, #619) (replaces `manual_scrobble.html` popup with song info popup in edit-mode)
- [X] User track play-count
- [ ] Ban/unban song from scrobbling (referencing Unique ID)
- [ ] Pause/resume scrobbling ( #616, #1196 )

Potential discussion points: usefulness of displaying things like total track time (see above screenshot) or [album name](https://www.dropbox.com/s/6ipeknczic05y90/Screenshot%202015-08-24%2015.03.48.png?dl=0) (see commented out code in /popups/info.html)?

### CODE REVIEW

**Comment by david-sabata** [comment]
Just a note (without looking into code) - how does the editing work? 
The bottom screenshot shows two edit icons which I think starts two separate editings and potentially two separate processing, correct?

The variant with single pencil icon on the bottom looks better imho :)

**Comment by janbaykara** [comment]
@david-sabata The two screenshots are from the same version. 

1. You click the pencil to enter *edit-mode*
2. The artist/song fields become editable and are highlighted in black/with pencil mark
3. Finally you click the floppy/save icon to commit the changes, and the popup returns to normal mode

**Comment by janbaykara** [comment]
@david-sabata The two screenshots are from the same version. 

1. You click the pencil to enter *edit-mode*
2. The artist/song fields become editable and are highlighted in black/with pencil mark
3. Finally you click the floppy/save icon to commit the changes, and the popup returns to normal mode

**Comment by fedorg** [comment]
I got used to seeing a faint edit icon when hovering over the edit strings, then clicking on that icon and pressing enter after I'm done editing. It's unobtrusive and clean. Everybody will mechanically pass their pointer over the song title and notice the edit controls.
By the way, there's another way of skipping a scrobble - make "1:47 to scrobble" a link which when clicked, changes to "scrobble skipped", which is (obviously) also a link to "scrobbling disabled".
Thinking about it once again as it's written, it feels messier than ever. I still can't think of any clean and intuitive way of skipping or disabling scrobbling.

**Comment by janbaykara** [comment]
@fedorg Will people inherently know that the extension allows song data to be edited via point+click?

**Comment by fedorg** [comment]
@janbaykara check my fork out, editing is obvious IMO.

**Comment by janbaykara** [comment]
@fedorg I really like that. One problem: if you change both the track name + artist using the Enter key, you scrobble **twice more**, not *once* more. 

I.e. 


Feel like it might be worth keeping Enter as the input navigation key, and on the *last* Enter press, it reveals a 'Enter to Submit' prompt in the popup or something.

**Comment by david-sabata** [comment]
@janbaykara I think it should behave the same as "manually_scrobble" popup. Tab switches fields, enter submits

Also another idea - I think we could replace the old inputs popup with the song info :)

**Comment by janbaykara** [comment]
@david-sabata That's sorted now. I've merged in @fedorg's changes, and tweaked things to restrict multiple submissions. 
* Now, after editing Track, tab/enter takes you down to edit Artist, and then tab/enter submits.
* Clicking off any input also does that.

**Comment by janbaykara** [comment]
@david-sabata I'm basically happy with what I've got here now, unless you have any other suggestions?

**Comment by janbaykara** [comment]
@fedorg I'm probably not going to have time to finish this PR up tbh, so feel free to fork and submit it.

**Comment by alexesprit** [comment]
Closed as outdated.

**Pull request closed without merging**
