### PR TITLE
Update deezer.js

### PR DESCRIPTION
**Pull request by NAUSHNIK52**
Last 3 weeks scrobbling won't work for me. There is fix for scrobbling Deezer.
This is my first fix ever so don't hate me please.

### CODE REVIEW

**Comment by david-sabata** [comment]
Waiting to see how #541 resolves

**Comment by david-sabata** [comment]
Won't merge now. This fix works only for russian language version of Deezer and simultaneously breaks english version. 

An update to make this change for RU only is needed.

**Comment by NAUSHNIK52** [comment]
@david-sabata I am just checked another languages in interest. Now my fix works with English and Russian at same time. Maybe Deezer updated design for another countries? Test please.

**Comment by inverse** [comment]
Not a deezer user but I've just tested and the existing one is working in both EN and RU locales. Perhaps it's a geolocation rollout.

When putting `STATIC_VERSION` into the console what do you get returned? Here I'm getting `00342213` - Perhaps this is the build number.

**Comment by NAUSHNIK52** [comment]
@inverse Suprisely, original Deezer.js now works fine for me.

**Comment by janbaykara** [comment]
@NAUSHNIK52 if it works now, do you think it's worth closing this PR?

**Pull request closed without merging**
