### PR TITLE
Amazon update

### LINKED ISSUE #835: Chrome extension stop working with Amazon Music Player
The extension stop working with chrome 46.0.2490.86 m.
It say "play some music to get started", when I start the music you can  briefly see a magnifying glass and then shows the normal logo with "play some music to get started" again.
With Google Play Music the extension still works great, seems to be a problem with amazon music player
Extension version: 1.54

### PR DESCRIPTION
**Pull request by Paszt**
closes #835 & #821 & #847

### CODE REVIEW

**Comment by lourinaldi** [comment]
Thanks for fixing!

**Comment by eiapopeia** [comment]
I'd like to see that in the official code.

**Comment by lourinaldi** [comment]
:+1: @eiapopeia

**Comment by brarig219** [comment]
Forgive me if I'm being an idiot right now; not trying to be.  @lourinaldi could you give me some pointers on what to do next to get this working again?  I'm having no luck over here.

**Comment by lourinaldi** [comment]
I'm in the same boat, @brarig219. All I have to go on is [this comment](https://github.com/david-sabata/web-scrobbler/issues/847#issuecomment-163585536) which doesn't really help. Also, I don't really want to change the js manually. The fix belongs in the master branch. Ayo, @david-sabata?

**Comment by sayashr** [comment]
Still not working here.

**Comment by Zylinderkatze** [comment]
Still not working. My "amazon music" URL is German, btw. Might that be part of the issue?

https://www.amazon.de/gp/dmusic/cloudplayer/web/

**Pull request merged**
