### PR TITLE
vk.com beta design support (new.vk.com)

### PR DESCRIPTION
**Pull request by umountdevbrain**
v2 connector

### CODE REVIEW

**Comment by seyfer** [comment]
+1 
new version was released and now it's main VK version. should be merged

**Comment by ex47** [comment]
it doesn't work, is it?

**Comment by umountdevbrain** [comment]
It works fine with new design on new.vk.com
Look at the screenshot: https://mswzeq.dm2304.livefilestore.com/y3mvtoV2vrdHKN1KY_5irG2sa42k6xGJ8WYfeFOmjGG7zJACDBaJ-Zo2CnBvFP2MfCMdFcX74qF6VQUwEogVe6XJ4uEe3lGtuiXdatTDddaka1cZYTUhdTi9C0lWBlfAUpez6LIL56zxMNw_xj0ZArKZTWVvOb5kxDSZ-S_jGFhFXY/2016-07-25.png?psid=1

**Comment by ex47** [comment]
Oh, it really works!
It's just that lines like `$('[data-is-current="1"]').data('audio')[5]` do not make much sense to me... 
Could you explain what it does?

**Comment by umountdevbrain** [comment]
Simple DOM parsing. First, get current song with $('[data-is-current="1"]') and after that check data-audio attribute:
0 - track id,
1 - user id,
2 - mp3 file URL,
3 - track name,
4 - artist name,
5 - duration.

**Comment by ex47** [comment]
yeah but
where did you get that `[data-is-current="1"]`

**Comment by ex47** [comment]
Ok, I get it now!
I basically did the same thing but using local storage.
screenshot_3

**Comment by umountdevbrain** [comment]
And you have created more efficient and universal solution. My code doesn't works when playlist on top of vk page or audio list invisible. I think I should close my pull request and download your version :)

**Comment by ex47** [comment]
Glad I could help!)

**Pull request closed without merging**
