### PR TITLE
Upgrade Soundcloud to V2 & new event-bus detection

### PR DESCRIPTION
**Pull request by Paszt**
New Soundcloud event-bus detection cycles through webpack modules to find the module with the correct functions instead of relying on the module number which will change each time they recompile the module. Also upgrade to V2 with getTrackArt  and getUniqueId methods included.

Should replace PR #645 (tried to fork that PR but couldn't).
ref #643

### CODE REVIEW

**Comment by inverse** [comment]
Much better :+1:

**Comment by AltarBeastiful** [comment]
Scrobbling is perfectly fine. We even gained track art!

I got 2 console logs : 
```
starter.js:52 Web Scrobbler: Connector.playerSelector is empty. The current connector is expected to manually detect state changes
starter.js:14 starter already loaded
```
They might be normal tought. 

@david-sabata What's the use of those?

**Comment by inverse** [comment]
@AltarBeastiful The first notice is more for developer reasons to indicate that the connector is using a non-conventional route of binding audio events. Normally it would be binding to the 'player' and watching for modifications but in this instance @Paszt has bound to the SC event bus.

The second notice  is because of the controller has already been started. Perhaps this is something we can avoid doing? @Paszt opinions?

**Comment by Paszt** [comment]
@inverse: I don't have a great understanding of the web-scrobbler core js, but I've just traced back the error.  It originates with the chrome.tabs.onUpdated event.  According to the [docs](https://developer.chrome.com/extensions/tabs#event-onUpdated), a tab status can be loading and complete.

I don't think it's anything in the connector but instead something different about soundcloud's website.

**Comment by david-sabata** [comment]
Great job, thanks!

**Comment by inverse** [comment]
:+1:

**Pull request merged**
