### PR TITLE
Update yandex-music.js

### PR DESCRIPTION
**Pull request by WhyamIdointhat**
Just want to add album's name in scrobble.

### CODE REVIEW

**Comment by alexesprit** [comment]
I found no elements by such CSS selector. Have you any example of URL where album info is available?

**Comment by WhyamIdointhat** [comment]
So extension itself already scrobble album name, but time to time.
On this page album name is correct
https://music.yandex.ua/album/1611922
But here no album name at all
https://music.yandex.ua/album/2970031

**Comment by alexesprit** [comment]
> So extension itself already scrobble album name, but time to time.

I suppose the extension just grabs album name using Last.fm API. I still see no elements having `.album_type_player .track__album` selector.

**Comment by xyauhideto** [comment]
I had a try and would conclude that the general way to get the album title of the now-playing track is using  `XHR`.

``` javascript
Connector.getAlbum = () => {
	let url = $('track_type_player .track__cover').attr('href'),
		album = null;
	$.ajax({
		url,
		type: 'get',
		async: false,
		success: (data) => album = $(data).find('h1').text(),
    });
	return album;
}
```

But it will keep fetching even after getting the result. I wonder if it is worth doing.

Btw I found the `trackArt`.
```javascript
Connector.getTrackArt = () => {
    let text = $('.track_type_player .track-cover').attr('srcset');
    return 'http:' + text.split(' ').shift();
};
```

**Comment by alexesprit** [comment]
> I had a try and would conclude that the general way to get the album title of the now-playing track is using XHR.

Well, the extension will execute this code too often (about every 0,5...1 sec), so this is not acceptable.

**Pull request closed without merging**
