### PR TITLE
Add Feedbands connector.

### PR DESCRIPTION
**Pull request by jaccarmac**

### CODE REVIEW

**Comment by jaccarmac** [comment]
Tests added.

**Comment by alexesprit** [comment]
I suggest to grab current time and duration of now playing song using `timeInfoSelector` property (`#player-time`).

**Comment by jaccarmac** [comment]
Noted, I'll update the request soon.

**Comment by jaccarmac** [comment]
Updated.

**Comment by alexesprit** [comment]
Nice, thanks! 👍

**Pull request merged**
