### PR TITLE
New Digitally Imported connector now supports new website design

### PR DESCRIPTION
**Pull request by mikdmgo**

### CODE REVIEW

**Comment by inverse** [comment]
Looks good :+1:  However I am not sure about the version bump or changelog as that's something that @david-sabata  does when he makes the release.

Also since this is a new connector you might want to hook it up to to Grunt so that it goes linted.

**Comment by inverse** [comment]
There's no need to close this...

**Comment by mikdmgo** [comment]
I just wanted to create a new pull request without changes in version and changelog :)

**Comment by inverse** [comment]
You could always undo such changes and then rebase to squash them together and make it look as if it never happened :) 

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by mikdmgo** [comment]
Thanks

**Comment by david-sabata** [comment]
Indeed I don't like the changes :smile: 

You can keep this PR but please update it as @inverse said. Also please rename the connector file to something starting with `difm`, so we know it's related to current `difm.js`. That will be handy when the "old" di.fm closes down.

**Comment by mikdmgo** [comment]
Fuck yeah! My first squashing is done! :)

**Comment by david-sabata** [comment]
@mikdmgo nicely done :)

The web is closed beta, so I'll merge without testing. I'm sure t it works fine ;)

**Comment by inverse** [comment]
Awesome work @mikdmgo  :)

**Comment by Daniel15** [comment]
Ideally it'd be good to hook in to their JavaScript directly rather than scraping data from the HTML. I made a new Digitally Imported connector last year (#327) but I'm not sure if it still works with the new layout.

**Comment by Daniel15** [comment]
My old approach still works with the new di.fm player; try running this in the Chrome console in the new player:

```
$(document).on('metadata-track', function(evt, metadata) {
  console.log('*** METADATA RECEIVED: ', metadata); 
});
$(document).on('wp-stop', function(evt) {
  console.log('** STOP');
});
```
Then start playing a song.

This would result in the removal of ~60 lines of code from `difm2.js`, as all the parsing code isn't necessary (`metadata` already has the data in a structured format).

Perhaps I should rebase my old pull request?

**Comment by david-sabata** [comment]
Agree with @Daniel15 - events are always better. A PR would be nice :)

**Comment by Daniel15** [comment]
I can try to revive my one later this week, I'm not even sure if it still works with the latest version. On my computer I've been using my old branch and haven't merged master back into it for ages =P

**Comment by david-sabata** [comment]
No rush. Just make sure you fully test it. I'm not in the closed beta to test it myself, so this has to work on first shot ;)

**Pull request merged**
