### PR TITLE
Added lofi-radio.co connector

### PR DESCRIPTION
**Pull request by jakeoid**
Adding a basic connector for the lofi-radio website!

### CODE REVIEW

**Comment by jakeoid** [comment]
👌

**Comment by jakeoid** [comment]
That should fix things. 🤔

**Comment by alexesprit** [comment]
Yes, now test is passed for me.

> Also, please add an URL pattern w/o "www".

Well, I meant to add the pattern and keep the one with "www", like:
```js
	{
		label: 'Lofi Radio',
		matches: ['*://lofi-radio.co/*', '*://www.lofi-radio.co/*'],
		js: ['connectors/lofi-radio.js'],
	},
```

The extension doesn't recognize the website in certain case without this change (I type "lofi-radio.co" in the adress bar and Chrome redirects to http://www.lofi-radio.co, but the website is also available at http://lofi-radio.co).

**Comment by jakeoid** [comment]
oh I was certain I could do that, two moments.

**Comment by alexesprit** [comment]
Thanks 👍

**Pull request merged**
