### PR TITLE
Fix for user page playback

### PR DESCRIPTION
**Pull request by inverse**
refs #935

### CODE REVIEW

**Comment by Regenspaziergang** [comment]
This fix still gets the album name as the song title, just without the "noise"  (some `span` tag) that was in there before.

The actual tag to load the album name from on song title pages is the `<a class="fav-track-link" >...</a>` descendant of the album; or, equally valid, the `<span class="fav-track-static">...</span>`.

**Comment by inverse** [comment]
My bad - I was 1/2 a sleep. Are you sure you're change gets the currently playing track?

**Comment by Regenspaziergang** [comment]
Yes, absolutely. I use this myself now.

<div>
</div><div>
</div><div>-------- Ursprüngliche Nachricht --------</div><div>Von: Malachi Soord <notifications@github.com> </div><div>Datum: 06.04.16  14:43  (GMT+01:00) </div><div>An: david-sabata/web-scrobbler <web-scrobbler@noreply.github.com> </div><div>Cc: Regenspaziergang <felics_dombek@hotmail.com> </div><div>Betreff: Re: [david-sabata/web-scrobbler] Fix for user page playback (#937) </div><div>
</div>
My bad - I was 1/2 a sleep. Are you sure you're change gets the currently playing track?

---

**Comment by Regenspaziergang** [comment]
Could you please merge my proposed changes into this PR and tell the author that it works?

**Comment by inverse** [comment]
:+1: done

**Pull request merged**
