### PR TITLE
Added (most) RadioPlayer sites

### PR DESCRIPTION
**Pull request by mvinaround**
Added support back for the RadioPlayer sites... managed to get both radio player layouts working. Just need to get the BBC style ones working (as they have the ability to scrub back along the live audio stream)

### CODE REVIEW

**Comment by mvinaround** [comment]
Just added my own station as a connector... I own Delta Radio UK...

**Comment by alexesprit** [comment]
You can run `grunt eslint` to fix ESLint errors.

**Comment by mvinaround** [comment]
@alexesprit cheers :)

**Comment by alexesprit** [comment]
Added in master branch.

**Pull request closed without merging**
