### PR TITLE
delta radio connector

### PR DESCRIPTION
**Pull request by jonas-koeritz**
Added livestream.deltaradio.de support. Would be nice to add a configurable delay for scrobbling (more than half the track) to prevent premature scrobbling. The hosts are always talking during the first 10s of the song ;)

### CODE REVIEW

**Comment by alexesprit** [comment]
Is there a reason to use `isPlaying` function in getters?

**Comment by jonas-koeritz** [comment]
Nope, no special reason. Just wanted to encapsulate it. I can change this ;)

Alexey <notifications@github.com> schrieb am Fr., 27. Jan. 2017, 17:26:

**Comment by alexesprit** [comment]
> Nope, no special reason. Just wanted to encapsulate it. I can change this ;)

That would be better to use selectors instead of getters, especially if there's no certain reason to implement custom behaviour of connector.

Could you also fix linter errors? These errors can be automatically fixed by running `grunt lint` command.

**Comment by jonas-koeritz** [comment]
The getters for track and artist are used to make sure that the station is
not currently playing advertisement or news (they will show track info
nonetheless)

Alexey <notifications@github.com> schrieb am Fr., 27. Jan. 2017, 17:43:

**Comment by alexesprit** [comment]
I also noticed the connector resets song if song is paused.

I suggested some changes:
* Don't reset song on pause.
* Check if ad is playing only in getter functions.
* Don't allow to change song (don't confuse with song reset) if next track is shown on the page.
```diff
diff --git a/connectors/v2/deltaradio.js b/connectors/v2/deltaradio.js
index 20645171..7039b9f7 100644
--- a/connectors/v2/deltaradio.js
+++ b/connectors/v2/deltaradio.js
@@ -5,37 +5,30 @@
 Connector.playerSelector = '#mainWrapper';
 
 Connector.getArtist = function() {
-	if (isPlaying()) {
+	if (!isAdPlaying()) {
 		return $('#ActiveTitle .meta .artist').text();
 	}
 
-    return null;
+	return null;
 };
 
 Connector.getTrack = function() {
-	if (isPlaying()) {
-        return $('#ActiveTitle .meta .title').text();
+	if (!isAdPlaying()) {
+		return $('#ActiveTitle .meta .title').text();
 	}
 
-    return null;
+	return null;
 };
 
-
-
-function isPlaying() {
-    return musicIsPlaying() && checkPlayButtonIsStop() && checkTitle();
-}
-
-Connector.isPlaying = isPlaying;
-
-function checkPlayButtonIsStop() {
+Connector.isPlaying = function() {
 	return $('#BtnPlayPause a').hasClass('stop');
-}
+};
 
-function musicIsPlaying() {
-	return $('#ActiveTitle .meta .title').text() !== 'www.deltaradio.de';
-}
+Connector.isStateChangeAllowed = function() {
+	// Don't recognize song if next one is on the page
+	return $('#ActiveTitle h3').text() !== 'Als nächstes läuft';
+};
 
-function checkTitle() {
-    return $('#ActiveTitle h3').text() !== 'Als nächstes läuft';
+function isAdPlaying() {
+	return $('#ActiveTitle .meta .title').text() === 'www.deltaradio.de';
 }
```

Works fine for me, but I didn't tested it too much. Plus, the website changed song data in strange way.

The full connector code:
```js
'use strict';

/* global Connector */

Connector.playerSelector = '#mainWrapper';

Connector.getArtist = function() {
	if (!isAdPlaying()) {
		return $('#ActiveTitle .meta .artist').text();
	}

	return null;
};

Connector.getTrack = function() {
	if (!isAdPlaying()) {
		return $('#ActiveTitle .meta .title').text();
	}

	return null;
};

Connector.isPlaying = function() {
	return $('#BtnPlayPause a').hasClass('stop');
};

Connector.isStateChangeAllowed = function() {
	// Don't recognize song if next one is on the page
	return $('#ActiveTitle h3').text() !== 'Als nächstes läuft';
};

function isAdPlaying() {
	return $('#ActiveTitle .meta .title').text() === 'www.deltaradio.de';
}
```

**Comment by jonas-koeritz** [comment]
Looks good to me. I agree, they're changing the track data in strange timings. Sometimes the page skips a song completely but basic scrobbling is correct.

**Comment by mvinaround** [comment]
Can we name this Delta Radio DE? Because I'm adding another Delta Radio (UK) as a connector... (deltaradiouk.co.uk)

**Comment by alexesprit** [comment]
Looks like the connector doesn't work due to website changes.

**Comment by jonas-koeritz** [comment]
Thanks for the notice. I think I will have a look at this tomorrow.

Alexey <notifications@github.com> schrieb am Di., 4. Apr. 2017, 17:46:

**Comment by alexesprit** [comment]
Added in 4f2050041bc72bebf32c15e4e174ea87eb0ee720.

**Pull request closed without merging**
