### PR TITLE
Connectors implementation

### PR DESCRIPTION
**Pull request by cermakjn**
Add Youradio.cz, Evropa2.cz, Europa2.sk, Frekvence1.cz, Radiobonton.cz and Danceradio.cz connectors.

Via issue #875

### CODE REVIEW

**Comment by david-sabata** [comment]
I have to ask - what is the purpose of those copyright notes?

I'm afraid this would prevent anyone else to make changes to the code you contribute and that is something I definitely want to avoid.

**Comment by cermakjn** [comment]
Hi David, there is internal rule to put copyright to our "public" scripts. 

For this situation, copyright is not necessary and could be removed, if you want.

**Comment by david-sabata** [comment]
Would be better, thanks

**Comment by cermakjn** [comment]
Copyrights has been removed.

**Pull request merged**
