### PR TITLE
Listen to events generated by VK player

### PR DESCRIPTION
**Pull request by f1u77y**
`window.ap` send player events in vk, so we must inject a script that
will listen to events from this object

### CODE REVIEW

**Comment by alexesprit** [comment]
Why do we need to listen to this event? I think it's easy enough to watch DOM changes.

**Comment by f1u77y** [comment]
@alexesprit we are already listening events generated by player node but it does not generate any events on "progress", so we have to either listen to `window.ap` or emulate "progress" by executing timer. I think first is better

**Comment by alexesprit** [comment]
Yes, you're right, events are better than timers.

But since we use VK events to watch playback state, watching DOM changes is useless. So, `Connector.playerSelector` should be undefined.

**Comment by f1u77y** [comment]
@alexesprit got it, will update pr asap

**Comment by alexesprit** [comment]
What about removing `updateTrackInfo` calls in every metadata getter and placing it before `Connector.onStateChanged`?

**Comment by inverse** [comment]
@f1u77y could you sort out the conflicts with the manifest please?

**Comment by f1u77y** [comment]
@inverse done

**Comment by inverse** [comment]
That was quick, cheers!

**Pull request merged**
