### PR TITLE
Update Google Music connector

### PR DESCRIPTION
**Pull request by TheQwerty**
Album art and track title IDs changed recently.

### CODE REVIEW

**Comment by TheQwerty** [comment]
Hmm... I just reloaded the tab that I had music playing in earlier and now it's using the old IDs again, so I guess this was a premature PR.

It might be worth having both in the connector, but I'm not sure. :confused:

**Comment by Paszt** [comment]
I'm getting the new ids (and therefore non-functioning connector).  Maybe wait a day or two and see what pans out.  Using the function form and including both ids may be necessary.

**Comment by inverse** [comment]
They changed their UI?

**Comment by Paszt** [comment]
No UI change, just the ids of the track title & album art elements.  But they've now changed back for me as well so maybe this was just a temporary change that was reverted.

**Comment by TheQwerty** [comment]
Reopening since I spent the morning with the new IDs.
I've modified the connector to use functions with both selectors now (preferring the new), and also added a duration selector.

Hopefully when the family sharing plans finish rolling out things will stabilize some.

**Comment by remijouannet** [comment]
hi, is there reason why this fix hasn't been merge yet ?

**Comment by simondlr** [comment]
+1. Please merge & update the extension.

**Comment by inverse** [comment]
@david-sabata must be afk. He holds the keys.

**Pull request merged**
