### PR TITLE
Fixed connector for odnoklassniki.ru

### PR DESCRIPTION
**Pull request by roamn**
Change selectors;

### CODE REVIEW

**Comment by roamn** [comment]
Hi.
It's my first PR, so i hope it's all right.

**Comment by inverse** [comment]
@roamn  Awesome work on getting your first PR out there! Looking briefly at your code I can see one issue immediatel (which I will comment). Did you test this locally? You can create a new Chrome profile to load the unpacked extension and see how things work etc :)

**Comment by roamn** [comment]
@inverse I have 2 laptops (win), and 2-3 PC. All ok. I don't have more people who listen music on this site :)

**Comment by roamn** [comment]
@inverse Snapshots
1. http://prntscr.com/7uyiyu
2. http://prntscr.com/7uyjba

**Comment by inverse** [comment]
Nice :+1: I'm unable to verify as I don't have an account but the changes seem reasonable :wink:

**Pull request merged**
