### PR TITLE
Fix VK scrobbling

### LINKED ISSUE #1038: New vk.com design fails scrobbling
Hi!  Seems like after vk.com made new design, scrobbling is not working anymore.

### PR DESCRIPTION
**Pull request by alexesprit**
VK has released new design of their site, so newvk.js should be mapped to 'vk.com', not 'new.vk.com'. Resolves #1038 and #1045.

And now there is no way to return back to old version of site, so old v1 connector is useless.

Also, #215, #409, #470, #578 should be closed. These issues are related to old v1 connector.

### CODE REVIEW

**Comment by alexesprit** [comment]
Added decoding of HTML entities to prevent scrobbling of something like this:
image

And some cosmetic changes.

**Comment by inverse** [comment]
That whole local storage thing seems so odd :/

**Comment by ex47** [comment]
@inverse the vk uses localStorage to synchronize player status on multiple tabs resulting in DOM of the page sometimes lacking info about the song (e.g. when player is minimized)

**Comment by kizhaeff** [comment]
When the update scrobbling to working VK?

**Comment by kizhaeff** [comment]
When the update scrobbling to working VK?

**Comment by alexesprit** [comment]
When @david-sabata will release new version of the extension.

**Pull request merged**
