### PR TITLE
Nightwave Plaza support

### PR DESCRIPTION
**Pull request by youkoso**
Hello there! I made connector to my radio station. Can you accept this? :)

### CODE REVIEW

**Comment by alexesprit** [comment]
Works well! :+1:
Just a note: implementation of `getTrackArt` function can be simplified to:
```js
Connector.trackArtImageSelector = '.cover img';
```

**Comment by youkoso** [comment]
> Just a note: implementation of getTrackArt function can be simplified
Thank you. I change it.

**Comment by youkoso** [comment]
Hello again. How about merge? :)

**Comment by Jirevelaz** [comment]
Doesn't work now

**Pull request merged**
