### PR TITLE
Fix VK connector

### LINKED ISSUE #1162: Vk.com: suddenly stops scrobbling
Hello! Today I saw thats scrobbling stop working on Vk.com. I'm using Google Chrome 54.0.2840.99 m.

### PR DESCRIPTION
**Pull request by alexesprit**
Resolves #1162.

### CODE REVIEW

**Comment by f1u77y** [comment]
@alexesprit that DOM node seems to be on every VK page. Maybe we should consider using it as primary metadata source?

**Comment by alexesprit** [comment]
@f1u77y I'd prefer fetching the data from DOM node too, but it contains artist and track in one place, so the song metadata can be parsed incorrectly (although, such cases are pretty rare).

To be honest, I don't like this fallback; in this case we cannot see if localStorage keys are changed (that means the replays are broken).

**Comment by f1u77y** [comment]
@alexesprit 
> it contains artist and track in one place, so the song metadata can be parsed incorrectly

See #1143, that should fix a lot of that cases

> we cannot see if localStorage keys are changed

I've also found the `audio` object that seems to be more reliable then `localStorage` keys

**Comment by alexesprit** [comment]
> See #1143, that should fix a lot of that cases

Yes, but we should implement this feature first. I have no idea how to do that atm.

> I've also found the audio object that seems to be more reliable then localStorage keys

Do you know how to get the data from this object? Or is it impossible?

**Comment by f1u77y** [comment]
> Do you know how to get the data from this object?

It has `id`, `performer`, `title` and `duration` keys(but we need to send it from vk-dom-inject script because it's not in DOM)

Progress could be got with `ap._impl._currentAudioEl` which is an `<audio>` node but I dunno if it's more stable than `localStorage`

**Comment by alexesprit** [comment]
I didn't find out how to get progress percentage, but I implemented fetching metadata from the audio element.

**Comment by f1u77y** [comment]
Something like [this](https://github.com/f1u77y/web-scrobbler/tree/vk-audio-elem-metadata-source)

**Comment by alexesprit** [comment]
Looks neat!

Is it worth opening a new PR with your patch instead of this one?

**Comment by alexesprit** [comment]
Closed in favor of #1164.

**Pull request closed without merging**
