### PR TITLE
Retina icons & setPageAction error checking

### LINKED ISSUE #811: Retina pageAction icons are pixelly
Fussy, minor issue, but on my retina screen the icons look pixelly, like so:

screen shot 2015-10-17 at 10 53 54

Could fix this by providing double-resolution icon files. @Paszt, thoughts?

### PR DESCRIPTION
**Pull request by Paszt**
Replaced page action png icons with svg, except loading icon which just didn't look good as svg.  For loading icon, added 38px format for double scale (iOS retina) support.  Still included loading svg file (page_action_loading.svg) which is the source for the pngs but isn't used directly by the extension. page_action_base.png remains - it's used as the favicon for the options page.

In setPageAction - added check to see if tab exists before performing the functions on it.  If it doesn't exist then only one information is output to the console where many errors were output before.

Also wrapped longer lines in pageAction.js.

closes #811

### CODE REVIEW

**Comment by david-sabata** [comment]
:+1: :+1: ... will wait for confirmation in #811 before merging

**Comment by inverse** [comment]
image

Looking like this on my browser

**Comment by Paszt** [comment]
The loading icons are already a dictionary so that one should display clean. The others are svg but  I guess chrome is converting the svg to bitmap then displaying it.  If you don't include the 38 path I guess it converts it to a 19px bitmap.  I'll make all the icons dictionaries.

**Comment by janbaykara** [comment]
You're awesome.

**Comment by david-sabata** [comment]
Super awesome! :heart_eyes:

**Comment by inverse** [comment]
:+1:

**Pull request merged**
