### PR TITLE
Create torch.js

### PR DESCRIPTION
**Pull request by tipar**
My first I would like to test it first before sending it but I do not know how. I am a total beginner here.

+'use strict';
+
+/* global Connector */
+
+Connector.playerSelector = '#td_player';
+
+Connector.artistSelector = '#artist';
+
+Connector.trackSelector = '.album_track_song';
+
+Connector.albumSelector = '.album';
+
+Connector.currentTimeSelector = '.ytplayer-getCurrentTime()';
+
+Connector.durationSelector = '#yt_time_duration';
+
+Connector.trackArtImageSelector = '.album_cover_container';
+
+Connector.isPlaying = function () {
+	var playButtonImgFilename = $('#play-pause img').attr('src');
+	return playButtonImgFilename.indexOf('pause') !== -1;
+};

### CODE REVIEW

**Comment by alexesprit** [comment]
You should add new entry in the `connectors.js` file. I don't know for what website the connector is, so I cannot do that.

**Comment by tipar** [comment]
I am afraid that I have no clue of what you are saying. I mean, could you link the file or explain it for a _dummy_ as in the book series? because it is my first one and I did enough getting the code :). Thanks. The URL if you can do it, it is http://music.torchbrowser.com/ I thought that with the name of the connector would be enough _Torch.js_. Regard.

**Comment by alexesprit** [comment]
there's a `core/connectors.js` file where all connectors are listed. You should add your connector to that list.

**Comment by alexesprit** [comment]
I took a look at the connector, I noticed some elements having selectors used in the connector are missing on the page (e.g. elements contains artist name or track name).

Here is an updated connector:
```js
'use strict';

/* global Connector */

Connector.playerSelector = '#td_player';

Connector.artistSelector = '#player_links .artist';

Connector.trackSelector = '#player_title';

Connector.albumSelector = '#player_links .album';

Connector.timeInfoSelector = '#div_time';

Connector.isPlaying = () => $('.player_btn.pause').length > 0;

Connector.getTrackArt = () => {
	let url = $('#player_thumb img').attr('src');
	if (url && url.indexOf('noimage') === -1) {
		return url;
	}

	return null;
};
```
This one works for me fine.

Plus I added this entry in the `connectors.js` file:
```js
{
	label: 'Torch Music',
	matches: ['*://music.torchbrowser.com/*'],
	js: ['connectors/torch.js']
}
```

**Comment by tipar** [comment]
So now? Been a couple of days and I can not scrobble yet.

**Comment by alexesprit** [comment]
I see no changes in the `connectors.js` file.

**Comment by tipar** [comment]
First, I copy/pasted the code you corrected on that pull request. And second you said you will do it. Maybe we have to wait a little or something?

> **Plus I added this entry in the connectors.js file:**

{
	label: 'Torch Music',
	matches: ['*://music.torchbrowser.com/*'],
	js: ['connectors/torch.js']
}

**Comment by alexesprit** [comment]
> And second, you said you will do it.

I meant I added these changes to get the connector worked. I haven't push it to master branch.

**Comment by inverse** [comment]
@tipar you need to paste that code @alexesprit mentioned into https://github.com/david-sabata/web-scrobbler/blob/master/core/connectors.js

**Comment by tipar** [comment]
@inverse Done. I assume the second one according to the page you send me, I hope I did not screw things up.

**Comment by alexesprit** [comment]
@tipar You pushed these changes to another branch (`patch-3`). This PR is from `patch-1` branch. you should push changes to `patch-1` to get them accepted. If you don't know how to do it, I can do it by myself, just let me know.

I suppose you're editing the code right on the Github, right?

**Comment by tipar** [comment]
@alexesprit Hi there. I had made the change from my repository to patch 1—I am so lost here, sorry—  anyway if there is something wrong, please, just tell me what exactly I did wrong so I will learn in case I want to do another one.

Just a doubt; I have seen that my changes on connectors of the second text, the one with the link to the page Torch, in this case, have been erased. I have to do it again or it does it automatically?

Regards.

**Comment by alexesprit** [comment]
> Just a doubt; I have seen that my changes on connectors of the second text, the one with the link to the page Torch, in this case, have been erased. I have to do it again or it does it automatically?

As I understand you that changes are not erased. they're in another branch. This PR is linked to `patch-1` branch.

**Comment by tipar** [comment]
So now?

**Comment by alexesprit** [comment]
I merged your changes and I'll update `connectors.js` by myself.

**Comment by tipar** [comment]
I wanted to do it by myself but go ahead then. So we will be able to scrobble from now or we have to wait or something? I mean, there is something left to do here by me?

**Comment by alexesprit** [comment]
You can install the extension as an unpacked one if you want scrobble from Torch right now. If you don't know how to install unpacked extensions, please use [this howto][1].

[1]: https://github.com/david-sabata/web-scrobbler#unpacked-extension

**Comment by tipar** [comment]
But is it mandatory to install the unpacked thing? I mean, it will not do it automatically from the Chrome Store app? And there is something left to do here by me? Regards.

**Comment by alexesprit** [comment]
> I mean, it will not do it automatically from the Chrome Store app?

Of course, the extension will be updated, but I don't know when.

**Comment by tipar** [comment]
OK. Thanks then, I assume there is nothing left for me to do here. Regards.

**Pull request merged**
